### ISSUE TITLE
Finish README.md

### ISSUE THREAD

**Issue by Ribby-0254** [Code2Gether-Discord/JokesOnYou#1]
**WHAT** 
  Open source projects often have a README.md file that is useful for giving users info on:
   - what the application is about
   - what technology is involved in the project
   - How to install/ run the application
   
 **WHY**
 In order to make it easier for new members to begin contributing to this project, having instructions on how to setup the project and what the project involves, will make the on boarding process easier for new members
 
 **HOW**
 We can use any open-source README.md as a template...heres one https://github.com/othneildrew/Best-README-Template

**Comment by HellHunterMax** [comment]
Don't forget to add a link to the wiki Page. There is some info there already.

**Comment by HellHunterMax** [comment]
We need a point of How to Work with Discord
