### ISSUE TITLE
Setup docker

### ISSUE THREAD

**Issue by Ribby-0254** [Code2Gether-Discord/JokesOnYou#10]
**WHAT**

Docker can be used to ship all dependencies required for the project, to all team members; so everyone is working with the same everything

**WHY**
To avoid issues with members having to install and manage dependencies.

**HOW**
- [ ] Members have to install docker
- [ ] dockerfile for frontend
- [ ] dockerfile for backend
- [ ] dockerfile for database
- [ ] docker-compose for everything
- [ ] setup dev environment with docker

**Comment by HellHunterMax** [comment]
If Anyone wants to pick this up or needs it or w/e you are welcome to work on it.
Don't forget to write a Document how to work with it and how you added it to the project. add it to the Wiki pls.
