### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#12]
This is a list of all models that need to be created.
There are separate issues for each model so we can discuss the models there. 
please add all fields to those as you think they are needed.

Main models:
- [x] User #13 
- [x] Joke #14 
- [x] Tag #15 
- [x] LikedJoke
- [x] SavedJoke
- [x] LikedTags
- [x] Flag #16 
- [x] Reason

If we come up with more models we will add them here.

**Comment by PoisnFang** [comment]
Would it be good to assign this to a specific person?
