### ISSUE TITLE
Convert the DTO concept into Request/Response models

### ISSUE THREAD

**Issue by bschaatsbergen** [Code2Gether-Discord/JokesOnYou#120]
Currently the sln is using DTO Models which are quite vaguely implemented, I would suggest refactoring these to Request/Response models.

A controller serializes to a XRequestModel and returns a XResponseModel.

**Comment by bschaatsbergen** [comment]
Very important, @chrisK00 will do it.

**Comment by bschaatsbergen** [comment]
noobs

**Comment by N1c0z** [comment]
smh
