### ISSUE TITLE
Make docker optional

### ISSUE THREAD

**Issue by chrisK00** [Code2Gether-Discord/JokesOnYou#164]
Docker makes more sense in a dev environment, but right now it is just slowing down the development process alot.

Make docker optional! One approach would be to have another connection string for a local postgre db and then we can simply switch the connection string for the AddDbContext.

https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli

**Comment by unbekanntunity** [comment]
:thumbsup:
