### ISSUE TITLE
Feature: add paging to Users.

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#187]
Right now when you Call the get Users  you get a list of all Users.
this needs to be limited with pages.

DONT USE THIS EXACTLY BUT IT MIGHT HELP:
https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/sorting-filtering-and-paging-with-the-entity-framework-in-an-asp-net-mvc-application

**Comment by ysnarafat** [comment]
Want to work on this issue.

**Comment by chrisK00** [comment]
> Want to work on this issue.

Sweet! Ive assigned it to you
