### ISSUE TITLE
Refactor: Change DateTime instances

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#189]
`This is an easy issue for people new to the project wanting to learn it or new to programming.`

#### "I'd recommend using `DateTime.Now` whenever you're displaying a date to a human being."
vs
## example:
Right now: Jokes saves to the Database Using DateTime.Now, this should be UtcNow.

## What to do:
Find all instances of DateTime and figure out which ones belong where.

## Source:
[datetime.now vs datetime.utcnow](https://stackoverflow.com/questions/62151/datetime-now-vs-datetime-utcnow)

**Comment by ysnarafat** [comment]
Looks interesting, want to work on this issue.

**Comment by HellHunterMax** [comment]
> Looks interesting, want to work on this issue.

Great if you need any help just call out on discord!

**Comment by ysnarafat** [comment]
The discord invitation link shows invalid. Will you place the invitation link here?

**Comment by chrisK00** [comment]
> The discord invitation link shows invalid. Will you place the invitation link here?

https://discord.gg/F3Z9EFadP5
