### ISSUE TITLE
Feature: GetTags using a JokeId

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#203]
the Website loads the jokes and then asks the backend for the tags associated with the joke.

use the UserTagJoke Model to find the tags Tagged with the Joke.

**Comment by talatmorshedtanbir** [comment]
Want to work on this

**Comment by HellHunterMax** [comment]
Great issue. though this one is in the backlog because it's not really possible yet. The tags need to be linked to the jokes which I'm implementing this week I hope.

**Comment by HellHunterMax** [comment]
The UserJokeTag has been merged with dev and this issue is now possible to make! good luck! if you need any help just ask here or on discord!

**Comment by talatmorshedtanbir** [comment]
Thanks. I will work on this
