### ISSUE TITLE
feature: Delete UserJokeTag

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#208]
The UserJokeTag should be deleted as soon as likes reaches 0;

**Comment by talatmorshedtanbir** [comment]
Can you explain which service will delete UserJokeTag? Is it Update Jokes Service? While updating like Count, if like count becomes 0, we need to delete the related UserJokeTag. Is it like that?

**Comment by HellHunterMax** [comment]
I'm sorry, I just saw that @JunXingLiu in #194 added this feature.

If you have a better idea of how to do this please do discuss with us.
