### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by Ribby-0254** [Code2Gether-Discord/JokesOnYou#21]
**WHAT**
  - A `CONTRIBUTING.md`  document serves to inform users on the guidelines, rules, and info on how to contribute to this project
  
**HOW**
  - Create a document based on this [auth0](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md) template (or use another popular one)

**Comment by code-reaper08** [comment]
Could you please assign this to me ?
I would love to work on this 😁

**Comment by chrisK00** [comment]
> Could you please assign this to me ?
> I would love to work on this 😁

Hey reaper! happy that you are willing to do this, are you in the discord server so i can add you to the chat channels

**Comment by code-reaper08** [comment]
> > Could you please assign this to me ?
> > I would love to work on this 😁
> 
> Hey reaper! happy that you are willing to do this, are you in the discord server so i can add you to the chat channels

Hello  !
Yup sure !

Username vizz#5421


Thanks for your quick reply 💯😇

**Comment by code-reaper08** [comment]
Hey could you please let me know Which license you use.
I would be a great help for the CONTRIBUTING.md I work on.

Thanks in advance.😃

**Comment by code-reaper08** [comment]
Hey I am sorry if I am late , Got stuck with some work , I'll create a PR today.

It would be good if you make me a assignee.

@chrisK00
