### ISSUE TITLE
Create User Model including Joke model

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#24]
From the ModelDiagram create the User model to be used in the backend.

**Comment by chrisK00** [comment]
If a users account gets deleted, do we delete all his jokes aswell? (cascade)

In order to start small and test features of the app i will create the User model only and we can expand on that like we decided. So we can test out authentication etc..

**Comment by HellHunterMax** [comment]
No user account will not be deleted completely just name changed to Deleted. and email will be deleted so we save the created jokes.

**Comment by HellHunterMax** [comment]
If a user gets banned we should keep the E-mail so the email cant be used again.
