### ISSUE TITLE
Create UserService

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#27]
Needs An Interface as well!
- [ ] GetAll
- [ ] GetById
- [ ] Create
- [ ] Update
- [ ] Delete

Docs:
- https://www.youtube.com/watch?v=fmvcAzHpsk8
- https://www.pointblankdevelopment.com.au/blog/134/aspnet-core-20-angular-24-user-registration-and-login-tutorial-example#user-service-cs

**Comment by PoisnFang** [comment]
cant we just use the built in identity framework the Microsoft has? https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0
