### ISSUE TITLE
Endpoint: Get User

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#78]
Create the whole line for Get User API call.

- [ ] GetUser inside controller HTTP get
- [ ] GetUser inside Service
- [ ] GetUser inside Repository

<details>
  <summary>How To / tips:</summary>

- Use UserManager from identity to get the user.

- Return UserReplyDto.
</details>

**Comment by Niisc** [comment]
Already did this in UserController.cs, you can find it in my PR. close issue?
