### ISSUE TITLE
Endpoint: Update User 

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#80]
Create the whole line for Update User API call.

- [ ] UpdateUser inside controller HTTP put
- [ ] UpdateUser nside Service
- [ ] UpdateUser inside Repository

<details>
  <summary>How To / tips:</summary>

- Use UserManager from identity to get the user.
- Use Automapper to map the Dto to the User
- Find out how to save to the DB
</details>

**Comment by Niisc** [comment]
Already did this in UserController.cs, you can find it in my PR. close issue?
