### ISSUE TITLE
Endpoint: Delete User

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#81]
Create the whole line for Delete User API call.

- [ ] DeleteUser inside controller HTTP Delete
- [ ] DeleteUser inside Service
- [ ] DeleteUser inside Repository

<details>
  <summary>How To / tips:</summary>

- Use UserManager from identity.
</details>

**Comment by Niisc** [comment]
Already did this in UserController.cs, you can find it in my PR. close issue?
