### ISSUE TITLE
Endpoint: Get Tag

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#86]
Create the whole line for Get Tag API call.

- [x] GetTag inside controller HTTP get
- [x] GetTag inside Service
- [x] GetTag inside Repository

Return a TagReplyDto

**Comment by heijmn** [comment]
I'm waiting for approval of PR #87 or PR #88 because they will add some fundamental stuff for Tags. Adding another PR with this will probably result in too many merge conflicts.
