### ISSUE TITLE
Feature: Give Joke a Tag

### ISSUE THREAD

**Issue by HellHunterMax** [Code2Gether-Discord/JokesOnYou#89]
A user should be able to Give a tag to a Joke. Any User should be able to do so.

Change the code To include each other.

- [ ] Joke Model
- [ ] User Model
- [ ] Tag Model
- [ ] Dto's for each
- [x] Inside Create Tag line add original user (creator)

**Comment by ofu997** [comment]
I believe the "Inside Create Tag line add original user (creator)" requirement is taken care of.

**Comment by HellHunterMax** [comment]
I'm gonna write some stuff down here so I don't forget and anyone can chime in if they want ;)
This needs:
a model with a DB tabel.
`TagToJokeLink` (or something else)
that holds the following fields : 
```
Id 
TagId
UserId
JokeId
TaggedDate
```
This need a controller with One Endpoint:
#### Add (Post)
This will be called when Adding a Tag to a joke. 
it will check for an Existing Tag by name if it exists will add the Tag to the joke. 
else it will create a new tag and then add it to the joke. 
Also it will add a LikeForTag entry for you.
